apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-predict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-predict
  template:
    metadata:
      labels:
        app: image-predict
    spec:
      containers:
        - name: image-predict
          image: image-predict
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
          env:
            - name: TZ
              value: "Europe/Brussels"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: image-predict-service
spec:
  selector:
    app: image-predict
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: LoadBalancer